### ISSUE TITLE
Potential issue with the images in the notification pop up

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#10]
@AddisonFreeman I just did an inspect to see what _could_ be the problem with the image sizes for the extension pop up notification window... maybe part of the problem is that you are constraining the maximum height alone and not the maximum width.  The width of the logo should be set to where it fills up the required area...  If you look at the images in the top left of both shop.complinks.co and xclub.complinks.co you'll see they loo OK there height wise, it's just the width, but they still look OK.

<img width="1209" alt="screen shot 2018-04-23 at 8 04 30 pm" src="https://user-images.githubusercontent.com/28393235/39159112-e43a5baa-4731-11e8-9aa3-13ff7597c60f.png">

<img width="1187" alt="screen shot 2018-04-23 at 7 50 32 pm" src="https://user-images.githubusercontent.com/28393235/39159120-edfc9ee6-4731-11e8-9d4c-d8a728444cbe.png">

**Comment by AddisonFreeman** [comment]
Just pushed 1.3.11 that fixes this.

**Comment by robgpeak** [comment]
WTF.  Now the pop up notifications are not even showing up, neither are our links above google search results for extension enabled advertisers.

**Comment by robgpeak** [comment]
Now it's showing up...  Not sure I did anything different...

**Comment by AddisonFreeman** [comment]
The latest push address slow loading and images are fixed as well.
