### ISSUE TITLE
We need to stop the pop up notification from showing up if the user came from our site

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#11]
I was just testing some links from our site to some advertiser's sites from some of the shop now buttons on our site, and the notification pop ups from the extension are showing up.  That's no good.  They should not show up if we already directed the user there from a link within our site.  

This may be a separate issue, but it should also NOT pop up if they reached the site from another affiliate like ebates or Southwest rapid rewards, etc.  and _they_ (ebates, southwest, etc.) have already activated a trip. 

Our notification pop up IS currently doing this, and that's not good either...
<img width="586" alt="screen shot 2018-04-23 at 9 04 08 pm" src="https://user-images.githubusercontent.com/28393235/39160561-f6747032-4739-11e8-9832-a63c8f4ad34b.png">

**Comment by AddisonFreeman** [comment]
To clarify, this notification is appearing on a complinks subdomain? That shouldn't happen unless that subdomain is extensionEnabled and isAdvertiser equals true in the backend

**Comment by AddisonFreeman** [comment]
I think I understand. If a user is redirected to a shopping site from the complinks subdomain that means a trip has already been started and the popup does not need to be shown. @cgladue is it easy to add url parameters to this kind of redirect so that the extension can read them to know not to show the notification?

**Comment by AddisonFreeman** [comment]
@cgladue see previous comment.

Here's the url I got from starting a trip to walmart. I'm not certain what I can use from this that will be a part of every shopping trip. I suppose "affillinktype"? It would be even better if you could add something like &cl_redirect=1 to the url params

https://www.walmart.com/browse/jewelry/precious-metals/3891_4718514?page=2&u1=1577&oid=223073.10014185&wmlspartner=jLQ8qrFPMSA&sourceid=24881544402803250679&affillinktype=3&veh=aff#searchProductResult

**Comment by cgladue** [comment]
all the links you get should start with /trip/startNew  you shouldnt be
using any link that goes directly to the advertiser first...



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
@AddisonFreeman no we cannot modify those links at all and still be in compliance with the referral networks...  it could have unintended consequences with the reporting of purchase data...

i woud suggest that right before you send the user off to the link you store something in session data that says what domain they are going to then check that session state whenever a page loads to see if its on the same domain ... or, perhaps if you check the document.referrer value it should always be *.complinks.co/blahblahblah/something i would think.

**Comment by AddisonFreeman** [comment]
@cgladue the auto redirect is not working for me if I start a trip on a retailer from the shop.complinks.co page.

my other issue is document.referrer is empty on the navigated page, I read that can happen if the header isn't set from the referring page. 

I may just have to build a stack in the background script to keep track of sites visited just after referring pages were visited. However I can map if the referring url is a match to the current url to hide notifications from ebates sites as it's in the url...
<img width="454" alt="screen shot 2018-04-30 at 3 11 19 pm" src="https://user-images.githubusercontent.com/5950267/39447906-dfa5ba92-4c88-11e8-8c5f-4970ff684b7f.png">
complinks doesn't have a way to see where the referring page is going though (there's a param for walmart but not cvs):
<img width="1059" alt="screen shot 2018-04-30 at 3 13 20 pm" src="https://user-images.githubusercontent.com/5950267/39447977-1dcbe936-4c89-11e8-8316-fa2ea072a79c.png">
<img width="1172" alt="screen shot 2018-04-30 at 3 12 57 pm" src="https://user-images.githubusercontent.com/5950267/39447978-1de2d448-4c89-11e8-862b-14b6563a8442.png">

Can I get a field in checkDomain to tell me if the trip started internally (on the subdomain page)?

**Comment by AddisonFreeman** [comment]
@cgladue I cannot tell which retailer is activated on the complinks subdomain page just before it redirects. On the page itself I set a session variable after they click the button. And I cannot retrieve the session storage on the retailer page because it is constrained to be set/get on that domain only. 

What if the field was an activated timestamp, updated whenever a trip is started from anywhere. I can set the site to say the trip is active if it is within 30 seconds.

**Comment by AddisonFreeman** [comment]
@robgpeak so you know this is still an open issue. I don't know how easy it is to update Rakuten with changes but trips started on a complinks domain currently will not show activated in the popup or extension. I'm working on a solution that meets compliance, just want you to know the status.

**Comment by robgpeak** [comment]
"@robgpeak so you know this is still an open issue. I don't know how easy it is to update Rakuten with changes but trips started on a complinks domain currently will not show activated in the popup or extension. I'm working on a solution that meets compliance, just want you to know the status."

This is confusing to me.  Trips started from a complinks domain should NEVER show "activated" in the popup, it just happens in the background like it does from any shop now button on the site.  That is what the Interstitial is for.  It should have nothing to do with the extension at that point, unless I'm missing something.

**Comment by AddisonFreeman** [comment]
So the notification shouldn't appear at all on a trip started from a
complinks subdomain link? Not even for 5 seconds and then disappear?

**Comment by robgpeak** [comment]
That is correct.  Not even for 5 seconds.  Not at all.
