### ISSUE TITLE
Have the link on Google searches appear above ALL the links to that advertiser

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#12]
@AddisonFreeman if you do a search for https://www.google.com/search?q=pteco&oq=pteco you'll see that our links do NOT appear above the search results of subdomains of the enabled advertiser's sites, but they should.

<img width="751" alt="screen shot 2018-04-25 at 10 05 31 am" src="https://user-images.githubusercontent.com/28393235/39250992-397591ea-4870-11e8-94c2-3cf1c9b06c96.png">

**Comment by AddisonFreeman** [comment]
It looks like petco.com is working but stores.petco.com is not. Ill look
into.

On Apr 25, 2018 9:06 AM, "robgpeak" <notifications@github.com> wrote:

@AddisonFreeman <https://github.com/AddisonFreeman> if you do a search for
https://www.google.com/search?q=pteco&oq=pteco you'll see that our links do
NOT appear above the search results of subdomains of the enabled
advertiser's sites, but they should.

[image: screen shot 2018-04-25 at 10 05 31 am]
<https://user-images.githubusercontent.com/28393235/39250992-397591ea-4870-11e8-94c2-3cf1c9b06c96.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/robgpeak/CL-WebExtension/issues/12>, or mute the thread

**Comment by AddisonFreeman** [comment]
I have found a solution for this but it looks like stores.petco.com is not
set as a valid url in the backend. Which begs the question, should
subdomains be considered in the check domain call. A lot of times the
subdomain denotes the language of the site (es. pt. /espanol, portugese) or
can be a different site entirely (blog.shoppingsite.com) that doesn't have
any deals like the main site would.

**Comment by robgpeak** [comment]
I would rather have it cover the root domain and ALL the subdomains.  In
the shopping retail space that we are targeting, and with the users being
in the US, I think we will be OK.  So abc.target.com and xyz.target.com
would both yield a link from us in a google search, and a popup if someone
when there manually.

**Comment by AddisonFreeman** [comment]
I won't pass in the subdomain to the api and see if that works with how the back end is set up currently. If there is a site that only works with the subdomain (i.e. maps.google.com) then I would only be sending google.com in that case. It may be more robust to receive all three parts of the url and have the back end return true on a per site basis. Like a *.petco.com rule to allow any subdomain that is sent. @cgladue, your thoughts?

**Comment by AddisonFreeman** [comment]
@cgladue is this possible? I'm wanting to always send the full url (everything between the protocol like http:// or https:// and the / after .com or .net) 

so www.walmart.com
or shop.shoes.co.uk
^ in a case like that the back end might only accept shoes.co.uk, but Rob wants all subdomains to be valid. Can you apply a rule on your end to accept extra subdomains?

this is the best way for me to parse the url cause I can't know how many .'s are in the url.

**Comment by robgpeak** [comment]
I am going to chime in her in an attempt to clarify.

As of right now we are basing the showing or not showing the notification pop up and/or the link above the listing of extension enable "true" advertisers by the "Program URL" that is in our back end.

<img width="271" alt="screen shot 2018-04-26 at 12 23 50 pm" src="https://user-images.githubusercontent.com/28393235/39318673-bac23690-494c-11e8-9cff-7ed0363ca98e.png">

Here is where the tricky part comes in...

First, go do a search for "norton software" (while you have the ebates and possibly another shopping extension like southwest shopping rewards, so you can see what types of URLs show up in the search results to get a better idea of what we're dealing with...

So if we were to use only the portion of the URL before the first "." which is immediately followed by "co" and show the notification pop up and/or the link above the listing of extension enable "true" advertisers, I think that might be the best way to cover all our bases.

Again, we are mainly dealing with retail websites whose search results will primarily be from people search for items or services to buy.  It's not like the advertisers we are dealing with are going to have blogs and other informational types of pages that are going to show up in search results.

Then in my example (image) above, if the URL in the Program URL is http://buy.norton.com we would strip out "http://buy." and just show **norton.com** to Addison in the API so if someone went to *.norton.com or that URL appeared in any search results, our notification pop up and/or our link would show up above their search results listing.

After writing all this I realize this might not be the optimal solution for a number of reasons. Number one people might use. Net they might use. Org. I think maybe a better solution would be for us to be able to manually add additional program urls in the back end to cover such instances where an Advertiser uses multiple subdomains.

Example:
<img width="506" alt="screen shot 2018-04-26 at 12 42 56 pm" src="https://user-images.githubusercontent.com/28393235/39319545-66ed199c-494f-11e8-88ac-4d183127432f.png">

The main issue with that is I think this Program URL comes over in the API from some of the networks and thus overwrites what we would manually change it to.  I am 99% sure I changed http://walgreens.com/default.jsp to be just http://walgreens.com/, and then it changed back to include "default.jsp" (which I just removed again 5 minutes ago...)

Anyway @cgladue please give it some thought and let us know what you come up with as the best solution.

**Comment by AddisonFreeman** [comment]
Ok @cgladue let me know when this is working, I changed it on my end and www.bestbuy.com is showing false, I'll push it when checkDomain is updated.
<img width="1001" alt="screen shot 2018-04-26 at 2 37 23 pm" src="https://user-images.githubusercontent.com/5950267/39328027-893a555e-495f-11e8-9da4-cf9783cb5399.png">

**Comment by robgpeak** [comment]
Chad when you say "i will disable the updating of the field for existing
advertisers." Does that mean I can add other domains in there like I
originally talked about?

**Comment by cgladue** [comment]
no, thats going to be a fair amount of work to make it take multiples ...
is there an advertiser this is causing an issue for ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Yeah, a couple but don't worry about it for now just leave it as whatever
the program URL is I'll work with it

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
@AddisonFreeman Try it now ...

**Comment by AddisonFreeman** [comment]
Nice catch, will do.

**Comment by AddisonFreeman** [comment]
Just pushed this. 1.3.23, looks like it is loading faster!
