### ISSUE TITLE
Traffic from extension links are still displaying old shopping trip interstitial

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#13]
@cgladue I suppose this is something for you.  Not sure if you been installing and testing the latest extensions, so I made a screencast... https://screencast.com/t/ubl5Nh77xV

**Comment by cgladue** [comment]
ill take care of this...

**Comment by robgpeak** [comment]
That did not work.  I tried from both godaddy and macys, and after clicking on the activate button in the popup notification, this happened...
<img width="1255" alt="screen shot 2018-04-27 at 8 39 13 am" src="https://user-images.githubusercontent.com/28393235/39363017-b5f7ca62-49f6-11e8-8f44-0da6fcd17847.png">

**Comment by cgladue** [comment]
typo, now try it...

**Comment by robgpeak** [comment]
cool.  Working now.  Must have been those damn tiny little mice running across your keyboard.
