### ISSUE TITLE
Change the extension login screen functionality

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#14]
@AddisonFreeman is it possible to change the functionality of the extension login screen?

When someone clicks "Save", they get the message (see image below), and I would like it to read, "Success! You are logged into the {Partner_Name} Shopping Assistant." On the pages that we are going to promote the installation of the web extension, we are going to call it the Shopping Assistant...

Then once they are authenticated, the "Save" button would become a "Start Shopping" button, and it would take them to https://{partner_subdomain}.complinks.co

As of right now the UX is confusing because even though the save message in the green showed up, it disappears, and someone'e inclination is to click save again...

<img width="794" alt="screen shot 2018-04-25 at 2 05 39 pm" src="https://user-images.githubusercontent.com/28393235/39264316-94cd4638-4892-11e8-8b0c-c7e56f7eb250.png">

**Comment by AddisonFreeman** [comment]
Just pushed 1.3.14 that fixes this.

**Comment by robgpeak** [comment]
I just installed 1.3.14 and it still has the same functionality...  

Also, it still reads CompLinks Rewards Everywhere instead of 
Rewards Everywhere
Shopping Assistant

Could this be a cache issue?

**Comment by AddisonFreeman** [comment]
Most likely, try restarting the browser if you can.

**Comment by robgpeak** [comment]
still not working... https://screencast.com/t/Tz7bdyReUzhw

**Comment by robgpeak** [comment]
Ah, you never pushed 1.3.14, I am still on .13

**Comment by AddisonFreeman** [comment]
darn it, just pushed.

**Comment by robgpeak** [comment]
Ok.  I guess we cannot change the "save" button to "Start Shopping", but I can at least live with the fact that it does not try to save it again.

One more slight adjustment to the initial log in screen verbiage.  I would like a "." after password. and then on a new line underneath it, it will read, "You will only need to do this one time."
<img width="422" alt="screen shot 2018-04-25 at 6 41 09 pm" src="https://user-images.githubusercontent.com/28393235/39276854-edcb1334-48b8-11e8-9d1c-3d9dbe58e8fc.png">

**Comment by AddisonFreeman** [comment]
Pushed 1.3.15 adding all that, including changing Save to Start Shopping

**Comment by robgpeak** [comment]
I guess I should have been more clear.  On the first screen when someone enters their email and password, the button would "Save", and once their password has been successfully saved, the button would change to read, "Start Shopping", but ONLY if the link from someone click that button would take them to https://{partner_subdomain}.complinks.co.  If you cannot change where that button would like to, then you can just leave it as "Save".

**Comment by AddisonFreeman** [comment]
1.3.17, just pushed, adds this.

**Comment by robgpeak** [comment]
Very Nice!
