### ISSUE TITLE
the extension does not work right away

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#15]
Immediately after installing the extension and signing in, if I go to a new tab and do a search on Google our links do not show up. If I go directly to an Advertiser enabled site, our notification popup does not show up. If I open a new tab and go to xclub.complinks.co and navigate anywhere in the site (because I am already logged in), and then go to another tab and do a Google search our links then finally show up. That's bad UX we need to figure out a way to make it automatically work without someone needing to go to our site.

Please clear cache close your browser window reopen it and see if you could replicate exactly what I just did

**Comment by robgpeak** [comment]
Have a look...  https://screencast.com/t/TxRvCdomtSF

**Comment by AddisonFreeman** [comment]
1.3.15 is the latest one, I'm watching the screencast now.

**Comment by AddisonFreeman** [comment]
I'll look at this tonight, let's check in tomorrow. I'm working on the rest
of the phase 3 stuff as well, trying to get it knocked out quickly.

**Comment by robgpeak** [comment]
OK have a good night

**Comment by AddisonFreeman** [comment]
Just pushed 1.3.16 that fixes this. I had added caching to the google
result page but that wouldn't work if you hadn't been to an advertiser
page, so now it gets the data if it isn't cached.

**Comment by robgpeak** [comment]
NICE!!!
