### ISSUE TITLE
Normalize image dimensions

### ISSUE THREAD

**Issue by AddisonFreeman** [robgpeak/CL-WebExtension#17]
referenced this issue here: https://github.com/robgpeak/CL-WebExtension/issues/9#issuecomment-384733702

styling is breaking because of an inconsistency on image dimensions under the same field.

**Comment by robgpeak** [comment]
For now, let's leave the partner logos (complinks and parx casino xclub) the way they are in the the pop up notification windows.  As for the logos of the stores, let's set the maximum to be 40 high Max and the width to be 150 Max.  This is what we do for ALL the store logos on the site...  https://screencast.com/t/G3jtMCEIT

**Comment by AddisonFreeman** [comment]
Got it, thank you.
