### ISSUE TITLE
Handle User Authentication / Domain Detection

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CL-WebExtension#2]
Each call to get data will require the user to be logged in, either via the website or via the API, otherwise permission will be denied to unauthorized users.

**Comment by AddisonFreeman** [comment]
Currently the only required field for being logged in is email address. This could probably be done automatically if we have that information from a session cookie.

**Comment by AddisonFreeman** [comment]
Will both require a password?

**Comment by cgladue** [comment]
yes...




Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
@AddisonFreeman @robgpeak 

i think i may have a solution rob, and would let you show the link on the appstore and not make it private:

i created a page @ https://xclub.complinks.co/extension .. on there the link will be a link to the extension, when someone visits that page it sets a cookie with the current domain.  they would click the link to download and install the extension, the first thing the extension would do when it finished installing is it would navigate to https://shop.complinks.co/extensioninstalled, which will read that cookie and redirect back to the subdomain that the extension was clicked from, and then the user could do their thing from there...

does that make it work the way youwanted ?

**Comment by AddisonFreeman** [comment]
That sounds like it would work. You may even be able to ask for their email
address and add it to the extension whitelist before redirecting them so
you know only they can use that link.

**Comment by AddisonFreeman** [comment]
Assuming that whitelist process can be done programmatically.

**Comment by robgpeak** [comment]
Sounds to me like it would work Chad, but I would have to see it in action to make sure it is behaving the way we want.  As Addison said, if we could get the authenticated details into the extension automatically, that would be great too.

**Comment by cgladue** [comment]
the authenticated details meaning what ?  if they are logged in then addison can see the cookie

**Comment by robgpeak** [comment]
So then a person would NOT need to separately log into the extension (using the same email and password of course)?  Meaning, IF the person was already logged into their account at xclub.complinks.co, and then went to install the extension, they would NOT need to log into the extension because they are already logged into the site, and we can read that automatically yes?

**Comment by cgladue** [comment]
Yes, they have to either be logged in via the extension (which also logs
them into the website at the same time) or be logged into the website
(which loggs them into the extension at the same time)



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
OK cool.  @AddisonFreeman let's get 'er done and see how it functions.

**Comment by AddisonFreeman** [comment]
@cgladue The only cookie I'm reading from that page is from google analytics. I think it's because the HttpOnly flag is set on it. Can you control that? (From https://www.owasp.org/index.php/HttpOnly : "If the HttpOnly flag (optional) is included in the HTTP response header, the cookie cannot be accessed through client side script") 
<img width="672" alt="screen shot 2018-03-23 at 10 55 10 am" src="https://user-images.githubusercontent.com/5950267/37841258-49e7a48e-2e8d-11e8-9320-685f22447547.png">

**Comment by cgladue** [comment]
hmm, ok can you read the ChromeExtension Cookie after going to /extension
on one of the subdomains or is that not showing up either ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by AddisonFreeman** [comment]
Are you setting it specificially for chrome with with chrome.cookie.set?

**Comment by cgladue** [comment]
No, its just named "ChromeExtension" its just a normal cookie.



Chad Gladue
*DevNull Technology, LLC*

**Comment by AddisonFreeman** [comment]
@robgpeak I updated the login process, let me know if you find anything unintuitive. Note: you have to click the settings button to enter your email if you haven't logged in on the website. If you have logged in externally, you'll see this screen. @cgladue I'm using the getNews call to check authentication here. Can that return the current user's email address, or better yet will you make a getUser call that sends the currently logged in user's email and subdomain? (then we have a fallback in case the cookie doesn't read)
<img width="408" alt="screen shot 2018-03-26 at 4 35 44 pm" src="https://user-images.githubusercontent.com/5950267/37934446-dca564c2-3113-11e8-9b10-f2aa4af77455.png">

**Comment by robgpeak** [comment]
would i have to install a new version of the extension to see any changes
that you are talking about?

**Comment by cgladue** [comment]
Yeah be much better if I make it get user call for you I’ll do that I’ll send you details tonight

**Comment by cgladue** [comment]
ok you can use the API *POST* https://*{subdomain}*.
complinks.co/api/v1/getUserDetail

Response:
{
    "firstName": "Chad",
    "lastName": "Gladue",
    "email": "chadgladue@gmail.com",
    "pendingPoints": 0,
    "availablePoints": 97010.01,
    "accountNumber": 21,
    "partnerName": "CompLinks™",
    "partnerSubdomain": "shop"
}



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
i removed the point balance info fields from the checkdomain call and put them in the getUserDetail call it seems to make more sense there anyways.

**Comment by AddisonFreeman** [comment]
@robgpeak just update the latest version from the github repo. I'll push another version with more updates soon though so hold off.

**Comment by AddisonFreeman** [comment]
@cgladue can you add a timestamp field to getUserDetail for the last time the user logged into that subdomain?

**Comment by cgladue** [comment]
i can, it may not be accurate since once they are logged in, they dont need
to login ever again, so its not always accurate to last time they visited
the site



Chad Gladue
*DevNull Technology, LLC*

**Comment by AddisonFreeman** [comment]
I'm just trying to determine which rewards program should show up on the
extension in case a user logs into 2. This way I can make the most recent
log in always show.

**Comment by cgladue** [comment]
lastLogin should be in the response now, it can be null if they have never logged in before, otherwise DateTime

**Comment by AddisonFreeman** [comment]
![complinks_domain_loginout](https://user-images.githubusercontent.com/5950267/38268689-60682a0c-3744-11e8-813a-7bab193710fd.gif)

@robgpeak just pushed an update that finishes logging in and out of separate domains on the options page. See also the updated notification styling. I'm working on the "authenticated" response for the notification and popup button next.

**Comment by AddisonFreeman** [comment]
Yes, I'm about to push another update though, wait 10 minutes.

**Comment by AddisonFreeman** [comment]
Okay you can pull now, this is what you should see. Try closing and starting your browser again if it doesn't appear, could be an old cookie.
![activated-user-feedback-cl](https://user-images.githubusercontent.com/5950267/38278165-8820c326-3760-11e8-84b8-c0bf0fc364bb.gif)

**Comment by robgpeak** [comment]
Looking good on the pop up notification, but let's make the shadow of the Activate button match these settings in the image below so it is only offset in one direction to the bottom left.  And the shadow of the overall notification pup up should be the same except the offset should be 8 instead of 3 like the button.

<img width="265" alt="screen shot 2018-04-03 at 6 10 15 pm" src="https://user-images.githubusercontent.com/28393235/38278531-6b52df18-376a-11e8-925d-863350670a00.png">

**Comment by AddisonFreeman** [comment]
Just pushed again. I fixed this box shadow, enabled the correct font and
improved the code so that you can click on the activate button within the
popup and see it turn green (before it just reflected what the notification
click showed). I also fixed the 'x' on the notification and improved the
hiding logic, it won't come back for an hour if you x out of it.

**Comment by robgpeak** [comment]
My button did not turn green when I clicked on it right way until the confirmation pop up came back after the redirection and then was green showing me that my earning points was activated...

As for the 'x' logic, why would we do that?  Like southwest, I would just close the popup, but show it again if they came back to the site again right away.

Lastly, did you ask Chad about why all the other sites were not working even though the dashboard shows them as "Extension Enabled"?

**Comment by cgladue** [comment]
As a new do with finding the site based on the Eurorail I’ll fix it no worries it’s not I believe it’s on my end on your end so you just continue on

**Comment by robgpeak** [comment]
LMAO on your voice to text conversion.  Even though it is cryptic to some, I hear the real words you spoke loud and clear:)

**Comment by AddisonFreeman** [comment]
haha, 'URL' :p

Rob I fixed the notification response, it will turn green right as you
click it and then redirect showing you the activated notification for a few
seconds again.

I assumed the user would want it gone for that session if they 'x' out of
it. It would still return after an hour passed or the user restarts the
browser.

To confirm you want the x to just hide it until refresh?

**Comment by robgpeak** [comment]
"To confirm you want the x to just hide it until refresh?"  Yes that is correct, sort of.  I would not it want to appear again after an hour or any time period, but ONLY if they refresh.  And when I say refresh, I mean if they close the tab and open the advertiser's site again in another instance, the notification would be there again.

**Comment by AddisonFreeman** [comment]
My concern was that they are trying to use the site for a different purpose
and get annoyed with the notification. A refresh how I mean is the same as
clicking a link inside the page and browsing the site normally.

**Comment by robgpeak** [comment]
I'm not sure what you're trying to say. It should work just like Ebates
when someone clicks no thanks maybe later the notification goes away and
doesn't show up again unless they close the window and reopen the window or
tab and manually return to that advertisers site. Then and only then what
are notification show up again.

**Comment by AddisonFreeman** [comment]
Yes, that's exactly what it's doing. Closing the tab or the window resets
that and going back to the page again you'd see it again.

**Comment by robgpeak** [comment]
Perfect

**Comment by AddisonFreeman** [comment]
@cgladue Did getUserDetail change at all? I'm getting a 302 object moved response on it now.

**Comment by AddisonFreeman** [comment]
Just kidding, I found the issue. ^^
