### ISSUE TITLE
Not receiving the "Activated" popup notification

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#20]
I just went to https://www.saksoff5th.com and https://www.saksfifthavenue.com from the link listing above each of their google listings in search results, and I was met with the Activate notification popup, and I clicked it in each case, and it started a shopping trip as expected, but when I was redirected to the sites themselves, I did not see the popup notification to say that my points for this shopping trip had been "Activated"

**Comment by AddisonFreeman** [comment]
Just pushed 1.4.0 (time for a version number update) that fixes this.

This was because of a change I made to try and detect when a user came from the subdomain site, I reverted that change and am still discussing with @cgladue how to best implement issue #11
