### ISSUE TITLE
Setting up a CompLinks publisher account for Chrome webstore

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#21]
@AddisonFreeman based on what we were talking about with having the ability to allow the compliance team to have access to a developer version of our extension on the chrome store (so it would not be available or viewable by the public), I was just about to sign up and saw this... Do you know what this means?
<img width="1067" alt="screen shot 2018-05-01 at 4 11 09 pm" src="https://user-images.githubusercontent.com/28393235/39491635-07255df2-4d5b-11e8-86f5-f4dc24f12332.png">

**Comment by AddisonFreeman** [comment]
Okay, checking that out now. I had an outdated chrome version, one sec..

**Comment by robgpeak** [comment]
Regina from Rakuten just wrote back and said she is using version 66.0.33

**Comment by AddisonFreeman** [comment]
Just pushed 1.4.1 with a fix. I was able to replicate her issue and resolve
it on vers. 66.0.33 on my end.

**Comment by AddisonFreeman** [comment]
I changed the syntax of the manifest to be more specific so that error when
uploading should work now too, I suppose the web store is more strict that
unpacked extensions.

**Comment by robgpeak** [comment]
OK and what about the error message above in this thread when I tried to upload the zip file.  Is that fixed as well?

**Comment by robgpeak** [comment]
I just upload the latest fix 1.4.1 and I got the same message

**Comment by AddisonFreeman** [comment]
Did you add your email to the list of allowed users? It's working for me.

**Comment by robgpeak** [comment]
I did not have to add email addresses, I just set it up that it will work for anyone who has the link, but it is still hidden from view from the general public.  It's working now...
