### ISSUE TITLE
Adding additional subdomains to extension

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#22]
@cgladue In preparation for our visit with Caesars, I would like to show them a working demo of the extension with their brand in place, so I needed to have the totalrewards subdomain function just like the xclub subdomain.  I have already uploaded the little search results logo.

**Comment by cgladue** [comment]
um, i dont quite understand, i dont know which domains are logged into from my end .. that depends on whether or not the Authentication Cookie is on the users machine or not ... they could clear their cookies and instantly be logged out without me being notified.

**Comment by robgpeak** [comment]
It's fine for now being hard coded.  It is working as expected now.

**Comment by robgpeak** [comment]
@cgladue I have not heard from Addison on this and I need to get it sorted before my presentation tomorrow.  I went into the code where he has the variable of the subdomains to look for hard coded stuff for shop,xclub,totalrewards, and added foxwoods, to the three files that but when I do that now nothing works. Any ideas?

<img width="314" alt="screen shot 2018-05-22 at 1 10 03 pm" src="https://user-images.githubusercontent.com/28393235/40378423-7ce18e50-5dc1-11e8-9df5-01ac8a60cec6.png">

**Comment by AddisonFreeman** [comment]
Sorry I'm here. Will push this in 20 minutes.

**Comment by cgladue** [comment]
did you go into the extension in chrome and "reload" the retension after you made the change rob ?

**Comment by AddisonFreeman** [comment]
<img width="504" alt="screen shot 2018-05-22 at 12 15 19 pm" src="https://user-images.githubusercontent.com/5950267/40378658-d8c620f8-5db9-11e8-8765-c35e06ada965.png">
There are three places it needs to be added. @cgladue This could be put into an api endpoint at the shop domain so that rob can add new domains in the back end.

**Comment by robgpeak** [comment]
Those were the three files that I updated by making them all read var domains = ['shop','xclub','totalrewards','foxwoods'] but when I saved them and reloaded the extension, not only did foxwoods not work, but none of the others worked either.

Now that Addison is on the case, let me know when you guys get it sorted out.

**Comment by AddisonFreeman** [comment]
Sorry wrong screenshot. 
<img width="400" alt="screen shot 2018-05-22 at 12 24 00 pm" src="https://user-images.githubusercontent.com/5950267/40379268-5b5bd3d6-5dbb-11e8-9bf7-d0ac3478150d.png">

**Comment by AddisonFreeman** [comment]
[CL-WebExtension-feature-unbranded.zip](https://github.com/robgpeak/CL-WebExtension/files/2027838/CL-WebExtension-feature-unbranded.zip)
Here's the unbranded branch with foxwoods added. version 1.5.6.1

**Comment by AddisonFreeman** [comment]
Everything looks there on the unbranded version except for the foxwoods logo. The partnerIcon field in getUserDetail isn't complete.

<img width="416" alt="screen shot 2018-05-22 at 12 32 51 pm" src="https://user-images.githubusercontent.com/5950267/40379674-5f253d8a-5dbc-11e8-83d9-61a9cbf0cd42.png">
<img width="461" alt="screen shot 2018-05-22 at 12 31 25 pm" src="https://user-images.githubusercontent.com/5950267/40379675-5f395b12-5dbc-11e8-99f9-ed66806ef5f5.png">
<img width="423" alt="screen shot 2018-05-22 at 12 31 08 pm" src="https://user-images.githubusercontent.com/5950267/40379676-5f4a63f8-5dbc-11e8-92cc-a7950e4365b6.png">
<img width="641" alt="screen shot 2018-05-22 at 12 31 03 pm" src="https://user-images.githubusercontent.com/5950267/40379677-5f5a8ef4-5dbc-11e8-93ea-c7a7a4e14d3f.png">

**Comment by robgpeak** [comment]
OK I will take care of the icon.

Thanks
​,​


Rob

**Comment by robgpeak** [comment]
First, what was the difference again between the branded and unbranded version of the extension?  Next, the color of the buttons in the extension and notification popups are great, but the ones in the google search are not the right color.  They should be the blue like the ones in the extension itself.

<img width="689" alt="screen shot 2018-05-22 at 1 47 01 pm" src="https://user-images.githubusercontent.com/28393235/40380364-e56a6aa0-5dc6-11e8-9094-7d3bf29f2965.png">

**Comment by robgpeak** [comment]
@AddisonFreeman in addition to the question and issue above, so you know v. 1.5.6.1 is showing the notification popup on the advertiser's site even after they come from our site directly and have seen the interstitial.  You fixed in the past so that would not happen, but it's happening again.

**Comment by cgladue** [comment]
@AddisonFreeman @robgpeak 

i have added a new API call to get a list of all configured subdomains, the endpoint is:  

and an example of the response is:

`[
    {
        "partnerName": "Capital Club®",
        "subdomain": "doverdowns"
    },
    {
        "partnerName": "Foxwoods",
        "subdomain": "foxwoods"
    },
    {
        "partnerName": "CompLinks",
        "subdomain": "shop"
    },
    {
        "partnerName": "Xclub",
        "subdomain": "Xclub"
    },
    {
        "partnerName": "Total Rewards",
        "subdomain": "totalrewards"
    }
]`

**Comment by AddisonFreeman** [comment]
Rob, you wanted a generic title on the pop up window when logged out. I’ll
change the button to be the themed color tonight.

**Comment by AddisonFreeman** [comment]
As well as integrating the new api call.

**Comment by AddisonFreeman** [comment]
@robgpeak just pushed 1.6 that has the login from the api and fixed the google button colors. The notification should only appear and then disappear to show that a site has beet activated, if you're going to it after you click the activate button on a complinks domian. Can you give more specific info of what you're seeing happening?

**Comment by robgpeak** [comment]
OK, I see the google button colors fixed, and that will do it for the presentation...  I have to leave the house in 45 minutes and have other stuff to do, so I can't get into the other stuff at the moment, but I will do a screen cast later to show you.  Thanks.

**Comment by AddisonFreeman** [comment]
Cool, remember that the last logged in subdomain theme will show up when
you log out.

**Comment by robgpeak** [comment]
Never-mind on the other shit I was saying, not sure where my head was at.  One thing I wanted to see if you could change was the color of the FONT on the foxwoods Shop Now buttons in the extension popup AND the activate buttons, AND the google listing...

<img width="1049" alt="screen shot 2018-05-23 at 2 12 26 pm" src="https://user-images.githubusercontent.com/28393235/40443732-41532662-5e95-11e8-835d-d959965850b4.png">
<img width="681" alt="screen shot 2018-05-23 at 2 23 25 pm" src="https://user-images.githubusercontent.com/28393235/40443743-47828276-5e95-11e8-84b8-c5cdabef8bcf.png">
<img width="476" alt="screen shot 2018-05-23 at 2 23 45 pm" src="https://user-images.githubusercontent.com/28393235/40443759-4bff23ea-5e95-11e8-8650-c828f0fc44e3.png">

**Comment by AddisonFreeman** [comment]
Just pushed 1.6.1 to fix the text color. I overrode the complinks dark orange to white because it looks better
<img width="635" alt="screen shot 2018-05-23 at 3 26 19 pm" src="https://user-images.githubusercontent.com/5950267/40449375-e82f564c-5e9d-11e8-8cbb-30438e0b4f4b.png">
<img width="640" alt="screen shot 2018-05-23 at 2 57 14 pm" src="https://user-images.githubusercontent.com/5950267/40449376-e84458c6-5e9d-11e8-9068-e70d4e622548.png">
<img width="648" alt="screen shot 2018-05-23 at 2 44 29 pm" src="https://user-images.githubusercontent.com/5950267/40449377-e85adbb4-5e9d-11e8-8ddd-d4b75e50f912.png">
<img width="638" alt="screen shot 2018-05-23 at 2 43 50 pm" src="https://user-images.githubusercontent.com/5950267/40449378-e86c8d28-5e9d-11e8-80d0-13cac2d7adbb.png">

**Comment by robgpeak** [comment]
Ok

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
I just looked at them all, and I want all the text on ALL the "buttons" for
the extensions to be white EXCEPT the foxwoods ones should be dark like you
have in the mock up above.

The total rewards and the xclub button text need to be white.  They are too
hard to read being dark.

**Comment by AddisonFreeman** [comment]
1.6.2 push fixes this. Keep in mind if there is a new domain with a light color the text will be white be default.
