### ISSUE TITLE
Always using last know sub domain for extension look/feel/color

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#23]
@AddisonFreeman The same way the notification pop up must recognize somehow that I am logged into a particular subdomain so it can show the corresponding color and logo from the correct subdomain almost instantly, we need to enable the same functionality into the extension window itself when someone click on the logo/icon in their toolbar.  At the moment, it immediately shows the blue generic CompLinks, or unauthenticated color scheme, and then refreshes to the proper color and content for the subdomain, but it looks pretty bad when it does that.

There should be a way to make it "persistent" and consistent for the last know subdomain.  It will NOT be changing very frequently if at all by and end user.

Here you can see what I mean... https://screencast.com/t/OJqZVkJC26QV

**Comment by AddisonFreeman** [comment]
fixed and fixed retailer logo max-height
