### ISSUE TITLE
Adjusting the Stand Down issue

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#27]
@AddisonFreeman We need to give some thought as to how to NOT stand down when we are the ones directing the traffic to an extension enabled advertiser's site.

For example, if you do a google search for "school clothes specials" and see the link for Kohls will be https://www.kohls.com/catalog/school.jsp?CN=Activity:School which means the activation notification popup will NOT show up, and that will be confusing to users.

So we need to think about how we can determine that this traffic is our, and how we CAN show our pop up notification.

**Comment by AddisonFreeman** [comment]
Working on this.

**Comment by AddisonFreeman** [comment]
1.7 just pushed that fixes this 

screenshare https://drive.google.com/open?id=1ir_FkB1GHHDkf-VYzXV5Nsjqe2jjrhnS

I didn't explain this but it still stands down if you are on google then click on an ebates link. This just allows google straight to a page with "="'s in the url and other deals will go through their in between page first.

**Comment by robgpeak** [comment]
Yeah, but that still poses a problem for "Ads" that an advertiser may buy on google.  So for example if you do a search for "refrigerator pc richards" and see the "Ads words" ad and click on the link for PC Richards, it will will take you to their site, but our notification will pop up and that's no good.

**Comment by robgpeak** [comment]
OK, so I just watched your video, and I think we are half way there.  You mentioned that if you come from Google itself and there's an equals in the URL our notification will still show up, but we need to stand down if the URL contains this https://www.googleadservices.com/pagead/aclk?  If you can see it of course...

**Comment by AddisonFreeman** [comment]
just pushed 1.7.1, standing down on google ad links.
