### ISSUE TITLE
Which users have installed the extension?

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#29]
@cgladue we wanted to see who has actually installed the extension at any given time? That would be an attribute I would like to see in Intercom so we could do email messaging based on whether they do or do not have the plug in installed...

**Comment by cgladue** [comment]
can this be something thats only in intercom ?

**Comment by robgpeak** [comment]
Does that make it easier?  I'm no programmer, but either way, we would have to track it on our end to report it to Intercom anyway, no?  That being the case, it would make sense to be able to see it in our back end dashboard separate and apart from Intercom.  I would not want to become beholden to them to see our data.

So again, unless I am not clear on something, I would think it would be easy enough to track it on our side and then report it to Intercom in the API.

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/45713684-b5212100-bb5d-11e8-9270-86d533fda08b.png)

ok, now we are recording a date stamp on the user record for the user that updates to the last time they used the extension, if its null they have never used it or dont have it installed

@robgpeak

**Comment by cgladue** [comment]
@robgpeak right now its not visible anywhere, but the data is being collected.  would like to hear your recommendation on where in the backend you want to display it.

**Comment by robgpeak** [comment]
How about like this...
<img width="1049" alt="screen shot 2018-09-18 at 5 16 53 pm" src="https://user-images.githubusercontent.com/28393235/45717038-b7d44400-bb66-11e8-908f-8bd09129e060.png">

**Comment by robgpeak** [comment]
Ok.  And the date and time that it says it was last used, how is that determined?  Look at what time to says yours was last used.  It seems like it was just when I was in front of my computer, not necessarily using it to search for something...

**Comment by cgladue** [comment]
"used" means the browser is opened and being used with the extension installed.

**Comment by robgpeak** [comment]
Ok
