### ISSUE TITLE
Authenticate Call

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CL-WebExtension#3]
Base URL: https://{subdomain}.complinks.co

**Request**:
HTTP POST /api/v1/authenticate
{
	"email": "your@email.com",
	"password": "password_here"
}

**Response**
{
    "success": true
}

**Comment by cgladue** [comment]
This call will log the user into the website also if they arent already

**Comment by AddisonFreeman** [comment]
This is giving a 200 success even with an incorrect password. With incorrect params (no params) it still sends a 200 but the url changes to something about an internal error. I can probably work with this, but it's definitely not conventional, can we get a 4xx on incorrect creds?

**Comment by cgladue** [comment]
Sure let me look at this.  It’s thrown together and should at the very least return something in the json body indicating invalid password.   I’ll get back with you.
