### ISSUE TITLE
Update is not getting forced through

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#37]
Hey @AddisonFreeman please have a quick look at this video https://www.loom.com/share/a659aea600bb4aa0be1ee48e8967e176 and let me know if I'm doing something wrong.

**Comment by AddisonFreeman** [comment]
If you see that orange circle on the extension icon that means you have it installed locally. Try removing it and installing from the web store “add to chrome” link.

Then look at your ad metrics to see if impressions are back up.

**Comment by robgpeak** [comment]
thanks that was it.  it is working as expected.
