### ISSUE TITLE
Extension stopped working since new site went live yesterday

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#38]
@AddisonFreeman We launched a new site yesterday (facelift) that you can see at xclub.rewardseverywhere.co and shop.rewardseverywehre.co and since then the extension is not working.  Can you please look into that for me.

**Comment by cgladue** [comment]
@robgpeak i think i found the issue

the newer framework automatically upgraded the API to webAPI and caused som issues i set it back manually so this should work now, its just deploying to the server gimme a minute

**Comment by AddisonFreeman** [comment]
The entire extension? Or just for the new site users?

**Comment by cgladue** [comment]
@robgpeak ok can you try it now ?

**Comment by robgpeak** [comment]
leaving the gym now I'll be home in 10 minutes and I will test it and let
you know

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
Do I need to reinstall the extension?

>

**Comment by robgpeak** [comment]
OK, so if I go to a particular site (manually type in the URL) and then click on the extension icon, that will work to show me the  deals (image 1), but then if I click on the "Activate" button in the extension, I see image 2

It is also NOT showing up in the google search like it used to.  And that is the important part.

--
<img width="1166" alt="Screen Shot 2019-11-13 at 11 18 04 AM" src="https://user-images.githubusercontent.com/28393235/68782584-a3bf9180-0607-11ea-8a60-4f772c4f268e.png">

--

<img width="1216" alt="Screen Shot 2019-11-13 at 11 19 22 AM" src="https://user-images.githubusercontent.com/28393235/68782645-be920600-0607-11ea-8f2a-6f5ae4888b3b.png">

**Comment by cgladue** [comment]
ok i can fix the error in the screenshot i think one moment, as for google results not sure about that one i think thats more on the extension side

**Comment by cgladue** [comment]
@robgpeak ok the "Activate" button should now work

**Comment by robgpeak** [comment]
Yes it is working.  Thanks.

@AddisonFreeman any idea on what the problem might be in order to have the google search show the logo and activate buttons above the search results?

**Comment by cgladue** [comment]
i tested the "checkDomain" call to the API that the extension uses and it returns the right data ...

**Comment by AddisonFreeman** [comment]
It’s not currently? Where can I make a login to test?

**Comment by robgpeak** [comment]
I thought you had a test account?  afree1423@gmail.com on xclub.rewardseverywhere.co

**Comment by robgpeak** [comment]
it would have carried over your same login information

**Comment by AddisonFreeman** [comment]
Oh, right. I’ll check in 20 minutes.

**Comment by robgpeak** [comment]
OK thanks.  I have a presentation at 1:00pm, so I would love to get it
working prior to that.

>

**Comment by AddisonFreeman** [comment]
I’ll expedite myself.

**Comment by AddisonFreeman** [comment]
@cgladue @robgpeak 

I found one thing. The endpoint at https://'+domain+'.rewardseverywhere.co/api/v1/getUserDetail used to return {"status":"unauthorized"} when invalid and now it's returning an HTML response.

**Comment by cgladue** [comment]
ok i will change it now to retun that JSON if they are not logged in one moment

**Comment by AddisonFreeman** [comment]
I can also see that checkDomain is failing. 
<img width="547" alt="Screen Shot 2019-11-13 at 11 42 30 AM" src="https://user-images.githubusercontent.com/5950267/68789276-bf786700-060a-11ea-9d26-01905e91670b.png">

**Comment by cgladue** [comment]
checkdomain works fine if you are logged in

**Comment by AddisonFreeman** [comment]
The problem is I can't log into the extension when getUserDetail returns HTML. Maybe it takes some time to update.
<img width="845" alt="Screen Shot 2019-11-13 at 11 47 10 AM" src="https://user-images.githubusercontent.com/5950267/68789783-b936ba80-060b-11ea-9d01-9aada080e737.png">

**Comment by AddisonFreeman** [comment]
@cgladue CheckDomain is giving an internalError message with a 200 status code.

**Comment by cgladue** [comment]
ok what about now?

**Comment by AddisonFreeman** [comment]
Still getting the error. It may be related to needing the partnerStyle attribute that used to come from getUserDetail that's now missing.
<img width="564" alt="Screen Shot 2019-11-13 at 11 59 25 AM" src="https://user-images.githubusercontent.com/5950267/68791331-affb1d00-060e-11ea-8374-f54303d71551.png">

**Comment by cgladue** [comment]
ah, ok that could be it that attribute is gone now ... i didnt realize you used it 

now there is three new attributes in its place:

1. primaryColor
2. secondaryColor
3. buttonColor

they can be HEX or RGB  (#FEFEFE or RGB(123,122,111) )

**Comment by cgladue** [comment]
give me a minute i will add them in

**Comment by cgladue** [comment]
ok i added partnerStyle back in since you required it but its gonna be blank

i added the above three fields that should be used instead

**Comment by AddisonFreeman** [comment]
That should work only checkDomain is still failing.

xclub.rewardseverywhere.co/api/v1/checkDomain is sending everything as normal but it catches as failure even though it's a 200 status.
<img width="742" alt="Screen Shot 2019-11-13 at 12 30 45 PM" src="https://user-images.githubusercontent.com/5950267/68793142-4b41c180-0612-11ea-8eb2-9b9cc6c4fe08.png">

**Comment by cgladue** [comment]
checkDomain works for me 

can you try logging out and re-authenticate ?

**Comment by cgladue** [comment]
the input for this call is the following (this hasnt changed)

{
	"includeDeals": false,
	"domainName" : [ "www.walmart.com" ]
}

**Comment by AddisonFreeman** [comment]
That wasn't in there. Let me try that.

**Comment by cgladue** [comment]
includedeals will default to false if you dont send it so that one isnt required but the domainname is an array not a single value

**Comment by AddisonFreeman** [comment]
Correct, It is passed as an array currently.

**Comment by cgladue** [comment]
ok, well using Insomnia tester it isnt failing for me

**Comment by cgladue** [comment]
checkDomain call is returning data as i would expect ...

**Comment by AddisonFreeman** [comment]
Let me try on postman

**Comment by AddisonFreeman** [comment]
The error message on that request says parsererror.

**Comment by cgladue** [comment]
can you show a screenshot ?  cuz i am not getting that

**Comment by AddisonFreeman** [comment]
I think it's because I'm expecting json input and the response is not that(?)

**Comment by cgladue** [comment]
you shouldnt be getting anything other then json tho

**Comment by AddisonFreeman** [comment]
There is a checkDomain call coming from the extension popup that is working fine. I wonder if the issue is related to where the call originates from. In this broken case it is from a script on the page as opposed to the extension itself. I wonder if Google has restricted access somehow.

**Comment by AddisonFreeman** [comment]
That fixed it. Google is really cracking down on security. I had not heard of that being applied to their policy, and even stranger why it just started taking effect with the server update.

**Comment by AddisonFreeman** [comment]
@robgpeak I'll have a fix for you shortly.

**Comment by AddisonFreeman** [comment]
@robgpeak Final version 1.9.1 is working for me in testing.
[CL-WebExtension1.9.1.zip](https://github.com/robgpeak/CL-WebExtension/files/3843380/CL-WebExtension1.9.1.zip)

**Comment by robgpeak** [comment]
I installed it locally for now, and it works, but the color of the buttons do not match the colors of the buttons on the site for the subdomain.

Here are the colors of the buttons on the xclub subdomain...

<img width="1122" alt="Screen Shot 2019-11-13 at 3 42 33 PM" src="https://user-images.githubusercontent.com/28393235/68802770-86e98500-062c-11ea-9336-185c3824dba1.png">


Here are the colors of the buttons in the google search results, but they should match the color of the buttons on the site...

<img width="753" alt="Screen Shot 2019-11-13 at 3 42 10 PM" src="https://user-images.githubusercontent.com/28393235/68802816-a680ad80-062c-11ea-9828-800776735ade.png">

and the same for the buttons in the popup... They should be red like on the site...

<img width="775" alt="Screen Shot 2019-11-13 at 3 42 23 PM" src="https://user-images.githubusercontent.com/28393235/68802887-cadc8a00-062c-11ea-8db5-83fa254b54e4.png">

And finally in the extension itself... Same thing, they should be red.
<img width="596" alt="Screen Shot 2019-11-13 at 3 46 10 PM" src="https://user-images.githubusercontent.com/28393235/68802947-f0699380-062c-11ea-95e6-d57572d55ad9.png">

**Comment by cgladue** [comment]
GUESSING ADDISON NEEDS TO USE THE PARAMETERS FOR BUTTONCOLORCODE AND PRIMARYCOLORCODE TO STYLE THE EXTENSION

whoopsie, caps was on sorry!

**Comment by AddisonFreeman** [comment]
I think I've set it straight now. Here's v1.9.2 
[CL-WebExtension1.9.2.zip](https://github.com/robgpeak/CL-WebExtension/files/3843481/CL-WebExtension1.9.2.zip)

<img width="394" alt="Screen Shot 2019-11-13 at 3 04 18 PM" src="https://user-images.githubusercontent.com/5950267/68804299-06745580-0627-11ea-9600-5f7fa0c2bece.png">
<img width="402" alt="Screen Shot 2019-11-13 at 3 04 00 PM" src="https://user-images.githubusercontent.com/5950267/68804300-06745580-0627-11ea-87a7-0796bacbf8f9.png">

**Comment by AddisonFreeman** [comment]
Wait, the google buttons are still wrong.

**Comment by AddisonFreeman** [comment]
v1.9.3 and we're done here!

[CL-WebExtension1.9.3.zip](https://github.com/robgpeak/CL-WebExtension/files/3843518/CL-WebExtension1.9.3.zip)

**Comment by robgpeak** [comment]
Shit!

<img width="897" alt="Screen Shot 2019-11-13 at 4 44 15 PM" src="https://user-images.githubusercontent.com/28393235/68806977-f7949f80-0634-11ea-8aa2-1a4af048a7d6.png">

**Comment by cgladue** [comment]
last update went pretty quick tho right ?

**Comment by AddisonFreeman** [comment]
Yes, from what I could tell version 1.8.5 was using full permissions which means the original review was approved.

**Comment by robgpeak** [comment]
So are we using different permissions from 1.8.5 which did NOT need any additional review...?

**Comment by AddisonFreeman** [comment]
No, but for some reason it was still flagged.

**Comment by AddisonFreeman** [comment]
That message is different from the one before, I suspect they're changing their policies.

**Comment by AddisonFreeman** [comment]
Google has approved the extension.
