### ISSUE TITLE
Individual deals and promotions

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#40]
@AddisonFreeman @cgladue didn't it used to work where if I had the extension installed and went to a advertisers site which is active in our program, it would show the individual deals and promotions available for that merchant?  It does not do that anymore and I was wondering why.

**Comment by robgpeak** [comment]
@AddisonFreeman I never heard back from you on this?

**Comment by AddisonFreeman** [comment]
Hi Rob, I've pushed a version that fixes this. v1.9.9

**Comment by robgpeak** [comment]
Awesome
