### ISSUE TITLE
Links not showing in google search results

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#41]
@AddisonFreeman I hope you've been keeping well.

The links that normally show up in the google search results are no longer showing up.  Do you know if something changed?

https://www.loom.com/share/f9e7d194b158424998ff2800ab8b1f6b

Thanks,

Rob

**Comment by AddisonFreeman** [comment]
Hi Rob,

I’m on vacation with my dad this week but if I get to wifi at some point I’ll be able to look into it. It’s possible google changed their DOM on the search page or updated their security policy again.

Best,
Addison Freeman

**Comment by robgpeak** [comment]
No worries, no rush.  Enjoy your vacation.

**Comment by robgpeak** [comment]
Hi @AddisonFreeman I hope you enjoyed your vacation.  When you get a chance, can you please look into this and see what the issue might be?

**Comment by AddisonFreeman** [comment]
Can you send me the link to the chrome webstore listing? I need to be sure what version you’re using.

Addison Freeman

**Comment by robgpeak** [comment]
https://chrome.google.com/webstore/detail/rewards-everywhere-shoppi/biikhgpldoekknfibpcegkkhbbjkchnh?hl=en-US

**Comment by AddisonFreeman** [comment]
Hi Rob,

I was able to get the links to appear but there is some additional overhaul needed.

Is it possible to open a one hour contract to get this sorted and updated for you?

Best,
Addison Freeman

**Comment by AddisonFreeman** [comment]
Here is what I have so far if you’d like to test and see what if anything works on the google page at this point.

https://drive.google.com/file/d/1zswOWbhfgYQm9NahgUcQ4g8C999TqWFN/view?usp=sharing

Addison Freeman

**Comment by robgpeak** [comment]
It's working just fine based on the change you made.  Please do bill me for an hour.  That's totally fine.

**Comment by robgpeak** [comment]
Can/should I upload this one to the chrome store and replace the old one, or should I wait to hear back from you?  The only reason I ask is you mentioned this is what I have so far, so I didn't know if there was an additional adjustment you needed to make.

**Comment by AddisonFreeman** [comment]
I sent another version to your email. Here is it again v1.9.7 https://drive.google.com/file/d/1X4eOq3rfWeReLROiGhx1lph0J5jo9Hn2/view?usp=sharing

Addison Freeman

**Comment by robgpeak** [comment]
Cool I will update it now.

Thanks,

Rob

*Sent from my phone

**Comment by robgpeak** [comment]
@AddisonFreeman this was the message I got when the extension update was rejected...

Hi there,

We regret to inform you that the most recent submission of your item was rejected. Please find the details below.


Item name: Rewards Everywhere Shopping Assistant

Item ID: biikhgpldoekknfibpcegkkhbbjkchnh

Violation(s):

User Data Privacy:

Violation reference ID: Purple Nickel

Violation: Privacy policy link is broken or unavailable
How to rectify: Add a publicly accessible and working link to your privacy policy.

Relevant section of the program policy:
If your Product handles personal or sensitive user data, then your Product must post a privacy policy. (learn more)

Any suggestions on a fix?

**Comment by AddisonFreeman** [comment]
Did you provide a privacy policy for the extension. They're looking for it and can't find it. You should have one on complinks.co and submit a link to it when you submit the extension.

Addison Freeman

**Comment by robgpeak** [comment]
@AddisonFreeman It seems like the logos and links are not showing in the google search results any more.  Can you please investigate and fix it.  Thanks.

**Comment by AddisonFreeman** [comment]
Hi Rob, a few things changed on Google's end. Make sure this looks okay. It was about 40 minutes of work and I made it smarter so that it won't keep breaking when Google updates their DOM. I also updated the master branch of this repo with these changes. 

[CL-WebExtension-master.zip](https://github.com/robgpeak/CL-WebExtension/files/6024338/CL-WebExtension-master.zip)
