### ISSUE TITLE
Display Pending Points in the extension

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#42]
@AddisonFreeman In speaking with Chad he indicated that he does send through to you in the extension API the "Pending Points" balance.  In the red bar in the image below, can you please have it read: 

Hi <First_Name>, you have <Pending_Points_Bal> pending points and <Available_Points_Bal> available points

<img width="425" alt="Screen Shot 2021-02-27 at 9 52 52 AM" src="https://user-images.githubusercontent.com/28393235/109390925-7bce6d00-78e2-11eb-8810-17b5da8affa3.png">

**Comment by AddisonFreeman** [comment]
Pushed a fix for this. I had to make the popup window slightly wider to accommodate the extra text.

**Comment by robgpeak** [comment]
That's fine in making it wider.  Just thinking out loud here, what if the text in that area gets longer, can't it just wrap and expand that area down one more line of text?

**Comment by robgpeak** [comment]
Thanks, I just submitted the changes to the Chrome store.
