### ISSUE TITLE
Using the header on the partner promotions page

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#43]
@AddisonFreeman can you make the partner page with the coupons and offers load the header and points balance as well...
<img width="328" alt="partner page with header" src="https://user-images.githubusercontent.com/28393235/109518313-2330d880-7a78-11eb-9663-8e8b3a4163bf.png">

**Comment by AddisonFreeman** [comment]
I just pushed this. v1.9.10

**Comment by AddisonFreeman** [comment]
I see that, my apologies. I just pushed a fix, v 1.9.11

Addison Freeman

**Comment by robgpeak** [comment]
cool and thanks
