### ISSUE TITLE
checkDomain Call

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CL-WebExtension#6]
Base URL: https://{subdomain}.complinks.co

**Request**:
HTTP POST /api/v1/checkDomain
{
	"domainName" : "bestbuy.com"
}

**Response**
{
    "isAdvertiser": true,
    "extensionEnabled": true,
    "advertiserName": "Best Buy",
    "clickUrl": "https://shop.complinks.co/trip/start?aid=6712&lid=0&url=https%3a%2f%2fclick.linksynergy.com%2ffs-bin%2fclick%3fid%3djLQ8qrFPMSA%26offerid%3d492045.16468%26type%3d3",
    "logoUrl": "https://s3.us-east-2.amazonaws.com/complinks/logos/lg_38606.jpg",
    "reward": "up to 0.5 points/$1 spent",
    "availablePointBal": 99010.01,
    "pendingPointBal": 0
}

**Comment by AddisonFreeman** [comment]
Is it possible to have an "isActivated" field with this return? Rob asked for a activated display on the notification after the user clicks a button and I assume that's a state on the back end. I can read the url for params after redirect but then I got thinking it would be useful to know that they are in an activated session for subsequent pages in the process so I don't know the popup asking them to activate again.

**Comment by cgladue** [comment]
thats not a state i maintain on the backend, what hes referring to is when
you prompt the user to activate their trip, after they get redirected to
the advertiser, display a popup showing that the trip is in fact active,
from looking at ebates it looks like this is maintained is session state
for the extension and browser window because if you close all browser
windows and go back to the advertiser it dosnt show that a trip is active
anymore.



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
if the user were to activate and then close all windows and then go back,
it would prompt them to activate again.  But if they activate and keep the
windows open it shouldnt prompt them again for the duration of that
session.... or perhaps an expiration date if they are strange and never
close the tab and do a second purchase.



Chad Gladue
*DevNull Technology, LLC*

**Comment by AddisonFreeman** [comment]
@cgladue we're seeing a discrepancy in what is in the dashboard and what is returned from this checkDomain call. these screenshots are for the same call. vistaprint should be active for shop.complinks.co

<img width="582" alt="screen shot 2018-04-04 at 3 25 40 pm" src="https://user-images.githubusercontent.com/5950267/38332861-9e1a1738-381c-11e8-991b-f02bda680e8c.png">
<img width="683" alt="screen shot 2018-04-04 at 3 25 28 pm" src="https://user-images.githubusercontent.com/5950267/38332862-9e2e9d5c-381c-11e8-953d-1018eed84fbd.png">

**Comment by cgladue** [comment]
ok give me a bit to see why it didnt match



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
this should be working now

**Comment by cgladue** [comment]
@AddisonFreeman check out the other issue for details on the new checkDomain call signature.
