### ISSUE TITLE
google voice email extension

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#8]
This is the site that I use, and it works really well  https://www.google.com/intl/en/chrome/demos/speech.html but the copying and pasting of the stuff I dictate from their window to the email is a pain, and I was looking for an extension to do it...

I found this https://chrome.google.com/webstore/detail/email-dictation/eggdmhdpffgikgakkfojgiledkekfdce?hl=en but when I went to install it, it made some mention that it communicate with cooperating websites, and I was a little hesitant to install it.

He apparently has the source on github  https://github.com/gregsadetsky/email-dictation and I wanted to see if you could liik through it and make sure it is not going anywhere besides google.

I did notice some of the reviews say it was buggy, but like I said, the first link I referenced in this thread works really well, so I am not sure what to make of it...

**Comment by AddisonFreeman** [comment]
This is using Google's servers to translate to text. The extension says it doesn't use any other third party and that looks to be true. I guess it boils down to if you trust Google or not. I don't see anything fishy in the extension itself, it's basically a wrapper for what that page does but inside gmail.

**Comment by robgpeak** [comment]
Thanks
